apiVersion: {{ .Values.apiVersions.secret }}
kind: Secret
metadata:
  name: logzio-metrics-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  logzio-metrics-shipping-token: {{ .Values.secrets.logzioShippingToken }}
  logzio-metrics-listener: {{ template "logzio.listenerHost" . }}
  kube-state-metrics-port: 
  cluster-name: {{ .Values.secrets.clusterName }}
